### ISSUE TITLE
Install over previous installation

### ISSUE THREAD

**Issue by PhilipNelson5** [widavies/WinJump#4]
When installing a new version with a previous version installed I get an error: You cannot start application WinJump from this location because it is already installed from a different location. 

It would be great if the installer could work with an existing installation. At least add instructions to the readme about updating.
<details>
  <summary>Details...</summary>

```
PLATFORM VERSION INFO
	Windows 			: 10.0.22000.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9037.0 built by: NET481REL1
	clr.dll 			: 4.8.9037.0 built by: NET481REL1
	dfdll.dll 			: 4.8.9037.0 built by: NET481REL1
	dfshim.dll 			: 10.0.22000.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/<user>/Downloads/Release_1_4_0/WinJump.application

IDENTITIES
	Deployment Identity		: WinJump.application, Version=1.0.0.2, Culture=neutral, PublicKeyToken=4afb527a0f4087dd, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\<user>\Downloads\Release_1_4_0\WinJump.application resulted in exception. Following failure messages were detected:
		+ You cannot start application WinJump from this location because it is already installed from a different location.
		+ You cannot start application WinJump from location file:///C:/Users/<user>/Downloads/Release_1_4_0/WinJump.application it is already installed from location file:///C:/Users/<user>/Downloads/WinJump/WinJump.application. You can start it from location file:///C:/Users/<user>/Downloads/WinJump/WinJump.application or you can uninstall it and reinstall it from location file:///C:/Users/<user>/Downloads/Release_1_4_0/WinJump.application. If you reinstall the application, be aware that you might lose any customizations that you made to the application.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [02/20/2023 8:02:18 AM] : Activation of C:\Users\<user>\Downloads\Release_1_4_0\WinJump.application has started.
	* [02/20/2023 8:02:19 AM] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [02/20/2023 8:02:19 AM] System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- You cannot start application WinJump from this location because it is already installed from a different location.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ApplicationActivator.CheckDeploymentProviderValidity(ActivationDescription actDesc, SubscriptionState subState)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- You cannot start application WinJump from location file:///C:/Users/<user>/Downloads/Release_1_4_0/WinJump.application it is already installed from location file:///C:/Users/<user>/Downloads/WinJump/WinJump.application. You can start it from location file:///C:/Users/<user>/Downloads/WinJump/WinJump.application or you can uninstall it and reinstall it from location file:///C:/Users/<user>/Downloads/Release_1_4_0/WinJump.application. If you reinstall the application, be aware that you might lose any customizations that you made to the application.
		- Source: 
		- Stack trace:


COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```
</details>

**Comment by widavies** [comment]
It's now a single file executable, so no installing/uninstalling needed
